# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

permissions:
  pages: write      # to deploy to Pages
  id-token: write   # to verify the deployment originates from an appropriate source

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build -- --base-href /${{ github.event.repository.name }}/

    - name: Upload GitHub Pages artifact
      uses: actions/upload-pages-artifact@v2
      with:
        name: website
        path: "./dist/aimi-bingo/browser"

  deploy:
    # Add a dependency to the build job
    needs: build

    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: https://$GITHUB_REPOSITORY_OWNER.github.io/${{ github.event.repository.name }}

    # Specify runner + deployment step
    runs-on: ubuntu-latest
    steps:
    - name: Download GitHub Pages artifact
      uses: actions/download-artifact@v2
      with:
        name: website

    - name: Deploy GitHub Pages site
      uses: actions/deploy-pages@v1.2.3
      with:
        path: website
